ConfigError: ModelSchema classes requires a 'Config' subclass
Makes it a bit easier for newbies like me.

Signed-off-by: Sebastian Wagner <sebastian@inter.link>